/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui.test {
    export class TestSceneUI extends Scene {
		public h5_api_btn:Laya.Sprite;
		public canPlayAd:Laya.Button;
		public playAd:Laya.Button;
		public share:Laya.Button;
		public isLogin:Laya.Button;
		public login:Laya.Button;
		public getUserAvatar:Laya.Button;
		public showRanking:Laya.Button;
		public submitRanking:Laya.Button;
		public getRanking:Laya.Button;
		public getMyRanking:Laya.Button;
		public getNearRanking:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
}