/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.test {
	import laya.ui.*;
	import laya.display.*;
	import script.GameUI;

	public class TestSceneUI extends Scene {
		public var h5_api_btn:Sprite;
		public var canPlayAd:Button;
		public var playAd:Button;
		public var share:Button;
		public var isLogin:Button;
		public var login:Button;
		public var getUserAvatar:Button;
		public var showRanking:Button;
		public var submitRanking:Button;
		public var getRanking:Button;
		public var getMyRanking:Button;
		public var getNearRanking:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("test/TestScene");

		}

	}
}