/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.test {
	import laya.ui.*;
	import laya.display.*;

	public class TestPhysicsUI extends Scene {
		public var scoreLbl:Label;
		public var tipLbll:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("test/TestPhysics");

		}

	}
}